### login
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: application/json 
Content-Type: application/json

{
    "email": "pedro@mail.com",
    "password": "pedro123"
}
### registro
### perfil

GET http://127.0.0.1:8000/api/v1/auth/perfil
Accept: application/json
Authorization: Bearer 4|8aPSSZKT7OL3smY4eJVBjf3RiGzuePWEqubyzWqa

### logout
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 4|8aPSSZKT7OL3smY4eJVBjf3RiGzuePWEqubyzWqa