### Lista de usuarios
GET http://127.0.0.1:8000/api/admin/usuario

### Nuevo Usuario
POST http://127.0.0.1:8000/api/admin/usuario
Accept: application/json
Content-Type: application/json

{
    "name": "Nitia",
    "email": "nitia@mail.com",
    "password": "nitia123"
}

### Mostrar Usuario

GET http://127.0.0.1:8000/api/admin/usuario/10

### Modificar Usuario
PUT http://127.0.0.1:8000/api/admin/usuario/3
Accept: application/json
Content-Type: application/json

{
    "name": "Ana Modificado",
    "email": "ana.prueba@mail.com",
    "password": "ana123456"
}

### Elminar Usuario
DELETE http://127.0.0.1:8000/api/admin/usuario/3



### CRUD

